# Univariate MLP Models

# Imports + Load Data

In [20]:
import math

from keras.layers import Dense
from keras.models import Sequential
from sklearn.metrics import mean_squared_error

In [2]:
BASE = '/Users/brinkley97/Documents/development/'
PATH_TO_BOOK = 'book-intro_to_tsf_with_python/'

# Converting Univariate Time Series (UTS) to Supervised Machine Learning (SML) problem

In [3]:
univariate_time_series = [10, 20, 30, 40, 50, 60, 70, 80, 90]
univariate_time_series

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [4]:
TS_AS_SML_FILE = BASE + PATH_TO_BOOK + '3-timeSeriesAsSupervisedLearning.ipynb'

In [5]:
# %load TS_AS_SML_FILE
/Users/brinkley97/Documents/development/book-intro_to_tsf_with_python/3-timeSeriesAsSupervisedLearning.ipynb

In [6]:
%run $TS_AS_SML_FILE

Input Univariate Time Series:
[ 1  2  3  4  5  6  7  8  9 10] 
X of size (10,)

Univariate Time Series as Supervised Machine Learning:
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10
X of size (7, 3)
y of size (7,)
     0    0    0   0
0  NaN  NaN  NaN   1
1  NaN  NaN  1.0   2
2  NaN  1.0  2.0   3
3  1.0  2.0  3.0   4
4  2.0  3.0  4.0   5
5  3.0  4.0  5.0   6
6  4.0  5.0  6.0   7
7  5.0  6.0  7.0   8
8  6.0  7.0  8.0   9
9  7.0  8.0  9.0  10
Input Univariate Time Series:
[10, 20, 30, 40, 50, 60, 70, 80, 90] 
X of size (9,)

Univariate Time Series as Supervised Machine Learning:
X_train: 
     t-3   t-2   t-1
3  10.0  20.0  30.0
4  20.0  30.0  40.0
5  30.0  40.0  50.0
6  40.0  50.0  60.0
7  50.0  60.0  70.0
8  60.0  70.0  80.0
y_train: 
     t
3  40
4  50
5  60
6  70
7  80
8  90


In [7]:
prior_observations, forecasting_step = [3, 1]
X_train_df, y_train_df, X_y_df = convert_uts_sequence_to_sml_with_pd(univariate_time_series, prior_observations, forecasting_step) 

Input Univariate Time Series:
[10, 20, 30, 40, 50, 60, 70, 80, 90] 
X of size (9,)

Univariate Time Series as Supervised Machine Learning:
X_train: 
     t-3   t-2   t-1
3  10.0  20.0  30.0
4  20.0  30.0  40.0
5  30.0  40.0  50.0
6  40.0  50.0  60.0
7  50.0  60.0  70.0
8  60.0  70.0  80.0
y_train: 
     t
3  40
4  50
5  60
6  70
7  80
8  90


In [8]:
X_train_df

t-3   t-2   t-1
3  10.0  20.0  30.0
4  20.0  30.0  40.0
5  30.0  40.0  50.0
6  40.0  50.0  60.0
7  50.0  60.0  70.0
8  60.0  70.0  80.0

In [9]:
y_train_df

t
3  40
4  50
5  60
6  70
7  80
8  90

In [10]:
X_y_df

t-3   t-2   t-1   t
3  10.0  20.0  30.0  40
4  20.0  30.0  40.0  50
5  30.0  40.0  50.0  60
6  40.0  50.0  60.0  70
7  50.0  60.0  70.0  80
8  60.0  70.0  80.0  90

In [11]:
X_train = X_train_df.values
print("X_train:", X_train)
y_train = y_train_df.values
print("y_train", y_train)

X_train: [[10. 20. 30.]
 [20. 30. 40.]
 [30. 40. 50.]
 [40. 50. 60.]
 [50. 60. 70.]
 [60. 70. 80.]]
y_train [[40]
 [50]
 [60]
 [70]
 [80]
 [90]]


# Create Keras model, fit, and predict

In [12]:
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=prior_observations))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

2023-06-06 08:54:56.408901: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [13]:
model.fit(X_train, y_train, epochs=2000, verbose=0)

In [39]:
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, prior_observations))
yhat = model.predict(x_input, verbose=0)
yhat

array([[100.5281]], dtype=float32)

In [40]:
yhat = yhat.tolist()
yhat = sum(yhat, [])
yhat

[100.5280990600586]

In [27]:
# root mean squared error or rmse
def measure_rmse(actual, predicted):
    # print("ACTUAL = ", actual)
    print("PREDICTED = ", predicted)
    return math.sqrt(mean_squared_error(actual, predicted))

In [41]:
ytrue = [100]
error = measure_rmse(ytrue, yhat) 
print('> %.3f' % error)

PREDICTED =  [100.5280990600586]
> 0.528
